name: Rego Tests
on: push
jobs:
  rego:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.23.0/conftest_0.23.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.23.0_Linux_x86_64.tar.gz
          mv conftest /usr/local/bin